routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/install', function () {
    \Illuminate\Support\Facades\Artisan::call('migrate:fresh', [
        '--seed' => true
    ]);
    \Illuminate\Support\Facades\Artisan::call('passport:install');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:super_admin|school_admin'])
    ->namespace('Backend')->prefix('admin')->name('admin.')->group(function () {

        Route::resource('/dashboard', 'DashboardController');

        Route::resource('/user', 'UserController');
        Route::post('/user/search', 'UserController@search')->name('user.search');

        Route::get('/user/assignSchoolModal/{entryID?}', 'UserController@assignSchoolModalIndex')
            ->name('user.assignSchoolModalIndex');
        Route::get('/user/assignClassModal/{entryID?}', 'UserController@assignClassModalIndex')
            ->name('user.assignClassModalIndex');
        Route::get('/user/assignChildrenModal/{entryID?}', 'UserController@assignChildrenModalIndex')
            ->name('user.assignChildrenModalIndex');

        Route::post('/user/assignSchoolModal/{entryID}', 'UserController@assignSchoolModalStore')
            ->name('user.assignSchoolModalStore');
        Route::post('/user/assignClassModal/{entryID}', 'UserController@assignClassModalStore')
            ->name('user.assignClassModalStore');
        Route::post('/user/assignChildrenModal/{entryID}', 'UserController@assignChildrenModalStore')
            ->name('user.assignChildrenModalStore');

        Route::middleware(['role:super_admin'])->group(function () {

            Route::resource('/role', 'RoleController');
            Route::post('/role/search', 'RoleController@search')->name('role.search');

            // School Admin Routes
            Route::resource('/school_admin', 'SchoolAdminController');
            Route::post('/school_admin/search', 'SchoolAdminController@search')->name('school_admin.search');

            // Parent Routes
            Route::resource('/parent', 'ParentController');
            Route::post('/parent/search', 'ParentController@search')->name('parent.search');

            // Class Routes
            Route::resource('/class', 'ClassController');
            Route::post('/class/search', 'ClassController@search')->name('class.search');

        });

        // Teacher Routes
        Route::resource('/teacher', 'TeacherController');
        Route::post('/teacher/search', 'TeacherController@search')->name('teacher.search');

        Route::get('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes')->name('school_admin.classes');
        Route::post('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes_store')->name('school_admin.classesStore');

    });

app/Http/Controllers/Backend/ClassController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Classes;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClassController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $classes = Classes::orderBy('id', 'desc')->paginate(15);
        if ($request->ajax()) {
            return view('admin.class.listing', compact('classes'));
        }
        return view('admin.class.index', compact('classes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:classes'
        ]);
        $class = Classes::create($request->all());
        return (isset($class->id)) ? response()->json(['bool' => true, 'message' => 'Class Added']) : response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|unique:classes,name,' . $id
        ]);
        $class = Classes::where('id', $id)->update($request->except(['_method', '_token', 'id']));
        return ($class) ?
            response()->json(['bool' => true, 'message' => 'Class Updated']) :
            response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $class = Classes::find($id);
        if (isset($class->id)) {
            $class->delete();
            return response()->json(['bool' => true, 'message' => 'Class Deleted']);
        }
        return response()->json(['bool' => false, 'errors' => ['Unable to delete class.']], 422);
    }

    public function search(Request $request)
    {
        $request->validate([
            'search' => 'required'
        ]);
        $classes = Classes::search($request->search)->paginate(15);
        return ($classes) ? view('admin.class.listing', compact('classes')) : response()->json(['bool' => false, 'errors' => ['No Class found']], 422);
    }
}

resources/views/admin/class/create.blade.php
<div class="modal fade" id="create_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{route('admin.class.store')}}" method="post" class="create-form">
                @include('admin.class.partial.form', ['label' => 'Create'])
            </form>
        </div>
    </div>
</div>

resources/views/admin/class/edit.blade.php
<div class="modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{route('admin.class.index')}}" method="post" class="edit-form">
                {{method_field('PUT')}}
                @include('admin.class.partial.form', ['label' => 'Edit'])
                <input type="hidden" name="id" id="id" value=""/>
            </form>
        </div>
    </div>
</div>

resources/views/admin/class/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Classes List
        <button class="btn btn-primary modalOpens" data-toggle="modal" data-target="#create_modal">Create
            Class
        </button>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active">Classes</li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                @include('admin.class.partial.searchForm')
            </div>
        </div>
        <div class="col-md-12">
            <div class="box">
                <div class="box-body" id="ajax-container">
                    @include('admin.class.listing')
                </div>
            </div>
        </div>
    </div>
    @include('admin.class.create')
    @include('admin.class.edit')
@stop

@section('css')
    @include('admin.css')
@stop

@section('js')
    @include('admin.javascript')
    <script>
        function ajax_request($url, $self, $method) {
            startLoading();
            $.ajax({
                url: $url,
                data: $self.serialize(),
                method: $method,
                success: function (data) {
                    var result = data;
                    $self.find('input[name="name"], input[name="description"], input[name="sort_order"]').val('');
                    $self.parents('div.modal').modal('hide');

                    new Noty({
                        type: 'success',
                        layout: 'topRight',
                        text: result.message
                    }).show();

                    renderHTML();

                    stopLoading();

                },

                error: function (data) {

                    stopLoading();

                    var result = JSON.parse(data.responseText);

                    $.each(result.errors, function (k, v) {
                        new Noty({
                            type: 'error',
                            layout: 'topRight',
                            text: v
                        }).show();
                    });
                }

            });
        }

        $(document).ready(function () {
            $('.create-form').submit(function (e) {
                e.preventDefault();

                var $url = $(this).attr('action'),
                    $self = $(this);

                ajax_request($url, $self, 'POST');

                return false;
            });
            $('.edit-form').submit(function (e) {
                e.preventDefault();

                var $url = $(this).attr('action') + '/' + $(this).find('input[name="id"]').val(),
                    $self = $(this);

                ajax_request($url, $self, 'PUT');

                return false;
            });

        });
    </script>
@stop

resources/views/admin/class/listing.blade.php
<table id="example" class="table table-bordered table-hover tablesorter customTableSort">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created At</th>
        <th>Action(s)</th>
    </tr>
    </thead>
    <tbody>
    @if (!empty($classes))
        @foreach ( $classes as $class )
            <tr id="class_{{$class->id}}">
                <td>{{$class->id}}</td>
                <td>{{$class->name}}</td>
                <td class="created_at">{{($class->created_at) ? $class->created_at->diffForHumans() : 'N/A'}}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-primary edit_entry modalOpens" title="Edit" href="#"
                           data-props="{{$class}}"
                           data-toggle="modal" data-target="#edit_modal">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a class="delete btn btn-sm btn-danger entry_remove"
                           data-route="{{route('admin.class.index')}}" data-entry_id="{{$class->id}}"
                           title="Delete">
                            <i class="fa fa-remove"></i>
                        </a>
                    </div>
                </td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="4">There is no Class.</td>
        </tr>
    @endif
    </tbody>
    <tfoot>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created At</th>
        <th>Action(s)</th>
    </tr>
    </tfoot>
</table>

{{ $classes->links() }}