routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/install', function () {
    \Illuminate\Support\Facades\Artisan::call('migrate:fresh', [
        '--seed' => true
    ]);
    \Illuminate\Support\Facades\Artisan::call('passport:install');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:super_admin|school_admin'])
    ->namespace('Backend')->prefix('admin')->name('admin.')->group(function () {

        Route::resource('/dashboard', 'DashboardController');

        Route::resource('/user', 'UserController');
        Route::post('/user/search', 'UserController@search')->name('user.search');

        Route::get('/user/assignSchoolModal/{entryID?}', 'UserController@assignSchoolModalIndex')
            ->name('user.assignSchoolModalIndex');
        Route::get('/user/assignClassModal/{entryID?}', 'UserController@assignClassModalIndex')
            ->name('user.assignClassModalIndex');
        Route::get('/user/assignChildrenModal/{entryID?}', 'UserController@assignChildrenModalIndex')
            ->name('user.assignChildrenModalIndex');

        Route::post('/user/assignSchoolModal/{entryID}', 'UserController@assignSchoolModalStore')
            ->name('user.assignSchoolModalStore');
        Route::post('/user/assignClassModal/{entryID}', 'UserController@assignClassModalStore')
            ->name('user.assignClassModalStore');
        Route::post('/user/assignChildrenModal/{entryID}', 'UserController@assignChildrenModalStore')
            ->name('user.assignChildrenModalStore');

        Route::middleware(['role:super_admin'])->group(function () {

            Route::resource('/role', 'RoleController');
            Route::post('/role/search', 'RoleController@search')->name('role.search');

            // School Admin Routes
            Route::resource('/school_admin', 'SchoolAdminController');
            Route::post('/school_admin/search', 'SchoolAdminController@search')->name('school_admin.search');

            // Parent Routes
            Route::resource('/parent', 'ParentController');
            Route::post('/parent/search', 'ParentController@search')->name('parent.search');

            // Class Routes
            Route::resource('/class', 'ClassController');
            Route::post('/class/search', 'ClassController@search')->name('class.search');

        });

        // Teacher Routes
        Route::resource('/teacher', 'TeacherController');
        Route::post('/teacher/search', 'TeacherController@search')->name('teacher.search');

        Route::get('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes')->name('school_admin.classes');
        Route::post('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes_store')->name('school_admin.classesStore');

    });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Nicolaslopezj\Searchable\SearchableTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;
    use SearchableTrait;
    use HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'phone_number', 'password', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $searchable = [
        'columns' => [
            'users.name' => 10,
            'users.phone_number' => 9,
            'users.email' => 8,
            'roles.name' => 7,
            'roles.display_name' => 6
        ],
        'joins' => [
            'role_user' => ['users.id', 'role_user.user_id'],
            'roles' => ['role_user.role_id', 'roles.id'],
        ]
    ];

    public function findForPassport($username)
    {
        return $this->where('phone_number', $username)->whereHas('roles', function ($query) {
            $query->whereIn('name', [
                'teacher',
                'parent'
            ]);
        })->first();
    }

    public function classes()
    {
        return $this->belongsToMany(Classes::class, 'school_class', 'school_id', 'class_id');
    }

    public function schools()
    {
        return $this->belongsToMany(User::class, 'school_teachers_students', 'teacher_student_id', 'school_id');
    }

    public function classTeacherStudent()
    {
        return $this->belongsToMany(Classes::class, 'class_teachers_students', 'teacher_student_id', 'class_id');
    }

    public function studentMeta()
    {
        return $this->hasMany(StudentMeta::class, 'student_id');
    }

    public function studentParent()
    {
        return $this->belongsToMany(User::class, 'student_parent', 'parent_id', 'student_id');
    }

    public function parentStudent()
    {
        return $this->belongsToMany(User::class, 'student_parent', 'student_id', 'parent_id');
    }

}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helper\UserHelper;
use App\Models\Classes;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{

    private $customData = [
        'title' => [
            'singular' => 'User',
            'plural' => 'Users'
        ],
        'routeName' => 'user'
    ];

    public function index(Request $request)
    {
        $users = UserHelper::getUsers();
        $roles = Role::all();
        $customData = $this->customData;
        if ($request->ajax()) {
            return view('admin.user.listing', compact('users', 'customData'));
        }
        return view('admin.user.index', compact('users', 'roles', 'customData'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = UserHelper::addUser($request);
        return (isset($user->id)) ? response()->json(['bool' => true, 'message' => 'User Added']) : response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = UserHelper::updateUser($request, $id);
        return ($user) ?
            response()->json(['bool' => true, 'message' => 'User Updated']) :
            response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if (isset($user->id)) {
            $user->delete();
            return response()->json(['bool' => true, 'message' => 'User Deleted']);
        }
        return response()->json(['bool' => false, 'errors' => ['Unable to delete user.']], 422);
    }

    public function search(Request $request)
    {
        $customData = $this->customData;
        $users = UserHelper::search($request);
        return (count($users) > 0) ? view('admin.user.listing', compact('users', 'customData')) : response()->json(['bool' => false, 'errors' => ['No User found']], 422);
    }

    public function assignSchoolModalIndex(Request $request, $entryID)
    {
        $schools = User::with('roles')->whereHas('roles', function ($query) {
            $query->where('name', 'school_admin');
        })->get();
        return view('admin.user.partial.assignSchoolModal', compact('schools', 'entryID'));
    }

    public function assignSchoolModalStore(Request $request, $entryID)
    {
        $user = User::find($entryID);
        $user->schools()->sync([$request->schoolID]);
        return response()->json(['bool' => true, 'message' => 'School Assigned with ' . ($user->roles()->first()->display_name) . ' Successfully.']);
    }

    public function assignClassModalIndex(Request $request, $entryID)
    {
        $classes = User::find($entryID)->schools()->first()->classes;
        return view('admin.user.partial.assignClassModal', compact('classes', 'entryID'));
    }

    public function assignClassModalStore(Request $request, $entryID)
    {
        $user = User::find($entryID);
        $user->classTeacherStudent()->sync([$request->classID]);
        return response()->json(['bool' => true, 'message' => 'Class Assigned with ' . ($user->roles()->first()->display_name) . ' Successfully.']);
    }

    public function assignChildrenModalIndex($entryID)
    {
//        $parent = User::find($entryID);
        // get all children's
        $students = User::whereHas('roles', function ($query) {
            $query->where('name', 'student_child');
        })->get();
        return view('admin.user.partial.assignChildrenModal', compact('students', 'entryID'));
    }

    public function assignChildrenModalStore(Request $request, $entryID)
    {
        $user = User::find($entryID);
        $user->studentParent()->sync([$request->studentID]);
        return response()->json(['bool' => true, 'message' => 'Student Assigned with ' . ($user->roles()->first()->display_name) . ' Successfully.']);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\UserResource;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{

    public function index(Request $request)
    {
        $user = $request->user();
        return new UserResource($user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getTeacherStudents(Request $request)
    {
        $teacher = $request->user();
        $school = $teacher->schools()->first();
        $class = $teacher->classTeacherStudent()->first();
        return UserResource::collection($class->teachersStudents()->whereHas('roles', function ($query) {
            $query->where('name', 'student_child');
        })->whereHas('schools', function ($query) use ($school) {
            $query->where('school_id', $school->id);
        })->get());
    }
}

resources/views/admin/user/partial/assignChildrenModal.blade.php
<div class="modal fade" id="assignChildrenModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{route('admin.user.assignChildrenModalStore', [
                'entryID' => $entryID
            ])}}" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Assign Children</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="studentID">Student</label>
                                <select name="studentID" id="studentID" class="form-control">
                                    @if (!empty($students))
                                        @foreach ( $students as $index => $student )
                                            <option value="{{$student->id}}" {{$index === 0 ? 'selected' : ''}}>{{($student->name)}}</option>
                                        @endforeach
                                    @else
                                        <option value="">No Student exists.</option>
                                    @endif
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {{ csrf_field() }}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary action-btn">Assign</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#assignChildrenModal form').submit(function (e) {
            e.preventDefault();
            ajax_request($(this).attr('action'), $(this), 'POST');
            return false;
        });
    });
</script>

resources/views/admin/user/partial/assignClassModal.blade.php
<div class="modal fade" id="assignClassModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{route('admin.user.assignClassModalStore', [
                'entryID' => $entryID
            ])}}" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Assign Class</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="classID">Classes</label>
                                <select name="classID" id="classID" class="form-control">
                                    @if (!empty($classes))
                                        @foreach ( $classes as $index => $class )
                                            <option value="{{$class->id}}" {{$index === 0 ? 'selected' : ''}}>{{($class->name)}}</option>
                                        @endforeach
                                    @else
                                        <option value="">No Class exists.</option>
                                    @endif
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {{ csrf_field() }}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary action-btn">Assign</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#assignClassModal form').submit(function (e) {
            e.preventDefault();
            ajax_request($(this).attr('action'), $(this), 'POST');
            return false;
        });
    });
</script>

resources/views/admin/user/partial/assignSchoolModal.blade.php
<div class="modal fade" id="assignSchoolModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{route('admin.user.assignSchoolModalStore', [
                'entryID' => $entryID
            ])}}" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Assign School</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="schoolID">School</label>
                                <select name="schoolID" id="schoolID" class="form-control">
                                    @if (!empty($schools))
                                        @foreach ( $schools as $index => $school )
                                            <option value="{{$school->id}}" {{$index === 0 ? 'selected' : ''}}>{{($school->name)}}</option>
                                        @endforeach
                                    @else
                                        <option value="">No School exists.</option>
                                    @endif
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {{ csrf_field() }}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary action-btn">Assign</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#assignSchoolModal form').submit(function (e) {
            e.preventDefault();
            ajax_request($(this).attr('action'), $(this), 'POST');
            return false;
        });
    });
</script>

resources/views/admin/user/partial/form.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">{{$label}} {{$customData['title']['singular']}}</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" id="name"
                       placeholder="{{$customData['title']['singular']}} Name"/>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email"
                       placeholder="{{$customData['title']['singular']}} Email"/>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="phone_number">Phone Number</label>
                <input type="text" class="form-control" name="phone_number" id="phone_number"
                       placeholder="{{$customData['title']['singular']}} Phone Number"/>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password"
                       placeholder="{{$customData['title']['singular']}} Password"/>
                <span class="help-block">Leave blank for default password (temp).</span>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-sm-9">
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" class="form-control" name="image" id="image"/>
                    </div>
                </div>
                <div class="col-sm-3 hidden-xs text-right">
                    <img src="{{asset('/images/userDefaultIcon.png')}}" image class="avatar-form">
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="roles">Roles</label>
                <select name="roles" id="roles" class="form-control">
                    @if (!empty($roles))
                        @foreach ( $roles as $role )
                            <option value="{{$role->name}}">{{($role->display_name) ? $role->display_name : $role->name}}</option>
                        @endforeach
                    @else
                        <option value="">No Role exists.</option>
                    @endif
                </select>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    {{ csrf_field() }}
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary action-btn">{{$label}}</button>
</div>

resources/views/admin/user/partial/searchForm.blade.php
<div class="box-header with-border searchFormHeader">
    <h3 class="box-title">Search Area</h3>
</div>
<form action="{{route('admin.'.$customData['routeName'].'.search')}}" method="post" class="searchForm">
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="search">Search</label>
                    <input type="text" class="form-control" id="search" name="search" placeholder="Search by any field">
                </div>
            </div>
        </div>
        {{--<div class="form-group">--}}
        {{--<label for="exampleInputPassword1">Password</label>--}}
        {{--<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">--}}
        {{--</div>--}}
        {{--<div class="form-group">--}}
        {{--<label for="exampleInputFile">File input</label>--}}
        {{--<input type="file" id="exampleInputFile">--}}

        {{--<p class="help-block">Example block-level help text here.</p>--}}
        {{--</div>--}}
        {{--<div class="checkbox">--}}
        {{--<label>--}}
        {{--<input type="checkbox"> Check me out--}}
        {{--</label>--}}
        {{--</div>--}}
    </div>
    <!-- /.box-body -->

    <div class="box-footer">
        {{ csrf_field() }}
        <button type="button" class="btn btn-default"
                onclick="(function(){ startLoading(); renderHTML(null, function(){ stopLoading(); }); }())">Reset
        </button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>