routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/install', function () {
    \Illuminate\Support\Facades\Artisan::call('migrate:fresh', [
        '--seed' => true
    ]);
    \Illuminate\Support\Facades\Artisan::call('passport:install');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:super_admin|school_admin'])
    ->namespace('Backend')->prefix('admin')->name('admin.')->group(function () {

        Route::resource('/dashboard', 'DashboardController');

        Route::resource('/user', 'UserController');
        Route::post('/user/search', 'UserController@search')->name('user.search');

        Route::get('/user/assignSchoolModal/{entryID?}', 'UserController@assignSchoolModalIndex')
            ->name('user.assignSchoolModalIndex');
        Route::get('/user/assignClassModal/{entryID?}', 'UserController@assignClassModalIndex')
            ->name('user.assignClassModalIndex');
        Route::get('/user/assignChildrenModal/{entryID?}', 'UserController@assignChildrenModalIndex')
            ->name('user.assignChildrenModalIndex');

        Route::post('/user/assignSchoolModal/{entryID}', 'UserController@assignSchoolModalStore')
            ->name('user.assignSchoolModalStore');
        Route::post('/user/assignClassModal/{entryID}', 'UserController@assignClassModalStore')
            ->name('user.assignClassModalStore');
        Route::post('/user/assignChildrenModal/{entryID}', 'UserController@assignChildrenModalStore')
            ->name('user.assignChildrenModalStore');

        Route::middleware(['role:super_admin'])->group(function () {

            Route::resource('/role', 'RoleController');
            Route::post('/role/search', 'RoleController@search')->name('role.search');

            // School Admin Routes
            Route::resource('/school_admin', 'SchoolAdminController');
            Route::post('/school_admin/search', 'SchoolAdminController@search')->name('school_admin.search');

            // Parent Routes
            Route::resource('/parent', 'ParentController');
            Route::post('/parent/search', 'ParentController@search')->name('parent.search');

            // Class Routes
            Route::resource('/class', 'ClassController');
            Route::post('/class/search', 'ClassController@search')->name('class.search');

        });

        // Teacher Routes
        Route::resource('/teacher', 'TeacherController');
        Route::post('/teacher/search', 'TeacherController@search')->name('teacher.search');

        Route::get('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes')->name('school_admin.classes');
        Route::post('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes_store')->name('school_admin.classesStore');

    });

app/Http/Controllers/Backend/ClassController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Classes;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClassController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $classes = Classes::orderBy('id', 'desc')->paginate(15);
        if ($request->ajax()) {
            return view('admin.class.listing', compact('classes'));
        }
        return view('admin.class.index', compact('classes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:classes'
        ]);
        $class = Classes::create($request->all());
        return (isset($class->id)) ? response()->json(['bool' => true, 'message' => 'Class Added']) : response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|unique:classes,name,' . $id
        ]);
        $class = Classes::where('id', $id)->update($request->except(['_method', '_token', 'id']));
        return ($class) ?
            response()->json(['bool' => true, 'message' => 'Class Updated']) :
            response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $class = Classes::find($id);
        if (isset($class->id)) {
            $class->delete();
            return response()->json(['bool' => true, 'message' => 'Class Deleted']);
        }
        return response()->json(['bool' => false, 'errors' => ['Unable to delete class.']], 422);
    }

    public function search(Request $request)
    {
        $request->validate([
            'search' => 'required'
        ]);
        $classes = Classes::search($request->search)->paginate(15);
        return ($classes) ? view('admin.class.listing', compact('classes')) : response()->json(['bool' => false, 'errors' => ['No Class found']], 422);
    }
}

resources/views/admin/class/partial/form.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">{{$label}} Class</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" id="name"
                       placeholder="Class Name"/>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    {{ csrf_field() }}
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary action-btn">{{$label}}</button>
</div>

resources/views/admin/class/partial/searchForm.blade.php
<div class="box-header with-border searchFormHeader">
    <h3 class="box-title">Search Area</h3>
</div>
<form action="{{route('admin.class.search')}}" method="post" class="searchForm">
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="search">Search</label>
                    <input type="text" class="form-control" id="search" name="search" placeholder="Search by any field">
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        {{ csrf_field() }}
        <button type="button" class="btn btn-default"
                onclick="(function(){ startLoading(); renderHTML(null, function(){ stopLoading(); }); }())">Reset
        </button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>