routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/install', function () {
    \Illuminate\Support\Facades\Artisan::call('migrate:fresh', [
        '--seed' => true
    ]);
    \Illuminate\Support\Facades\Artisan::call('passport:install');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:super_admin|school_admin'])
    ->namespace('Backend')->prefix('admin')->name('admin.')->group(function () {

        Route::resource('/dashboard', 'DashboardController');

        Route::resource('/user', 'UserController');
        Route::post('/user/search', 'UserController@search')->name('user.search');

        Route::get('/user/assignSchoolModal/{entryID?}', 'UserController@assignSchoolModalIndex')
            ->name('user.assignSchoolModalIndex');
        Route::get('/user/assignClassModal/{entryID?}', 'UserController@assignClassModalIndex')
            ->name('user.assignClassModalIndex');
        Route::get('/user/assignChildrenModal/{entryID?}', 'UserController@assignChildrenModalIndex')
            ->name('user.assignChildrenModalIndex');

        Route::post('/user/assignSchoolModal/{entryID}', 'UserController@assignSchoolModalStore')
            ->name('user.assignSchoolModalStore');
        Route::post('/user/assignClassModal/{entryID}', 'UserController@assignClassModalStore')
            ->name('user.assignClassModalStore');
        Route::post('/user/assignChildrenModal/{entryID}', 'UserController@assignChildrenModalStore')
            ->name('user.assignChildrenModalStore');

        Route::middleware(['role:super_admin'])->group(function () {

            Route::resource('/role', 'RoleController');
            Route::post('/role/search', 'RoleController@search')->name('role.search');

            // School Admin Routes
            Route::resource('/school_admin', 'SchoolAdminController');
            Route::post('/school_admin/search', 'SchoolAdminController@search')->name('school_admin.search');

            // Parent Routes
            Route::resource('/parent', 'ParentController');
            Route::post('/parent/search', 'ParentController@search')->name('parent.search');

            // Class Routes
            Route::resource('/class', 'ClassController');
            Route::post('/class/search', 'ClassController@search')->name('class.search');

        });

        // Teacher Routes
        Route::resource('/teacher', 'TeacherController');
        Route::post('/teacher/search', 'TeacherController@search')->name('teacher.search');

        Route::get('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes')->name('school_admin.classes');
        Route::post('/school_admin/classes/{school_id?}', 'SchoolAdminController@classes_store')->name('school_admin.classesStore');

    });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Nicolaslopezj\Searchable\SearchableTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;
    use SearchableTrait;
    use HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'phone_number', 'password', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $searchable = [
        'columns' => [
            'users.name' => 10,
            'users.phone_number' => 9,
            'users.email' => 8,
            'roles.name' => 7,
            'roles.display_name' => 6
        ],
        'joins' => [
            'role_user' => ['users.id', 'role_user.user_id'],
            'roles' => ['role_user.role_id', 'roles.id'],
        ]
    ];

    public function findForPassport($username)
    {
        return $this->where('phone_number', $username)->whereHas('roles', function ($query) {
            $query->whereIn('name', [
                'teacher',
                'parent'
            ]);
        })->first();
    }

    public function classes()
    {
        return $this->belongsToMany(Classes::class, 'school_class', 'school_id', 'class_id');
    }

    public function schools()
    {
        return $this->belongsToMany(User::class, 'school_teachers_students', 'teacher_student_id', 'school_id');
    }

    public function classTeacherStudent()
    {
        return $this->belongsToMany(Classes::class, 'class_teachers_students', 'teacher_student_id', 'class_id');
    }

    public function studentMeta()
    {
        return $this->hasMany(StudentMeta::class, 'student_id');
    }

    public function studentParent()
    {
        return $this->belongsToMany(User::class, 'student_parent', 'parent_id', 'student_id');
    }

    public function parentStudent()
    {
        return $this->belongsToMany(User::class, 'student_parent', 'student_id', 'parent_id');
    }

}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helper\UserHelper;
use App\Models\Classes;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{

    private $customData = [
        'title' => [
            'singular' => 'User',
            'plural' => 'Users'
        ],
        'routeName' => 'user'
    ];

    public function index(Request $request)
    {
        $users = UserHelper::getUsers();
        $roles = Role::all();
        $customData = $this->customData;
        if ($request->ajax()) {
            return view('admin.user.listing', compact('users', 'customData'));
        }
        return view('admin.user.index', compact('users', 'roles', 'customData'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = UserHelper::addUser($request);
        return (isset($user->id)) ? response()->json(['bool' => true, 'message' => 'User Added']) : response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = UserHelper::updateUser($request, $id);
        return ($user) ?
            response()->json(['bool' => true, 'message' => 'User Updated']) :
            response()->json(['bool' => false, 'errors' => ['Operation failed. Please try again.']], 422);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if (isset($user->id)) {
            $user->delete();
            return response()->json(['bool' => true, 'message' => 'User Deleted']);
        }
        return response()->json(['bool' => false, 'errors' => ['Unable to delete user.']], 422);
    }

    public function search(Request $request)
    {
        $customData = $this->customData;
        $users = UserHelper::search($request);
        return (count($users) > 0) ? view('admin.user.listing', compact('users', 'customData')) : response()->json(['bool' => false, 'errors' => ['No User found']], 422);
    }

    public function assignSchoolModalIndex(Request $request, $entryID)
    {
        $schools = User::with('roles')->whereHas('roles', function ($query) {
            $query->where('name', 'school_admin');
        })->get();
        return view('admin.user.partial.assignSchoolModal', compact('schools', 'entryID'));
    }

    public function assignSchoolModalStore(Request $request, $entryID)
    {
        $user = User::find($entryID);
        $user->schools()->sync([$request->schoolID]);
        return response()->json(['bool' => true, 'message' => 'School Assigned with ' . ($user->roles()->first()->display_name) . ' Successfully.']);
    }

    public function assignClassModalIndex(Request $request, $entryID)
    {
        $classes = User::find($entryID)->schools()->first()->classes;
        return view('admin.user.partial.assignClassModal', compact('classes', 'entryID'));
    }

    public function assignClassModalStore(Request $request, $entryID)
    {
        $user = User::find($entryID);
        $user->classTeacherStudent()->sync([$request->classID]);
        return response()->json(['bool' => true, 'message' => 'Class Assigned with ' . ($user->roles()->first()->display_name) . ' Successfully.']);
    }

    public function assignChildrenModalIndex($entryID)
    {
//        $parent = User::find($entryID);
        // get all children's
        $students = User::whereHas('roles', function ($query) {
            $query->where('name', 'student_child');
        })->get();
        return view('admin.user.partial.assignChildrenModal', compact('students', 'entryID'));
    }

    public function assignChildrenModalStore(Request $request, $entryID)
    {
        $user = User::find($entryID);
        $user->studentParent()->sync([$request->studentID]);
        return response()->json(['bool' => true, 'message' => 'Student Assigned with ' . ($user->roles()->first()->display_name) . ' Successfully.']);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\UserResource;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{

    public function index(Request $request)
    {
        $user = $request->user();
        return new UserResource($user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getTeacherStudents(Request $request)
    {
        $teacher = $request->user();
        $school = $teacher->schools()->first();
        $class = $teacher->classTeacherStudent()->first();
        return UserResource::collection($class->teachersStudents()->whereHas('roles', function ($query) {
            $query->where('name', 'student_child');
        })->whereHas('schools', function ($query) use ($school) {
            $query->where('school_id', $school->id);
        })->get());
    }
}

resources/views/admin/user/classes.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Classes List</h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active">Classes</li>
    </ol>
@stop

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-body" id="ajax-container">
                    <form id="classesForm" action="{{route('admin.school_admin.classesStore', [
                        'school_id' => $schoolID
                    ])}}" method="post" onsubmit="return false;">
                        <div style="overflow: hidden;">
                            @if(!empty($classes))
                                @foreach ( $classes as $class )
                                    <div class="col-sm-2 col-xs-3">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"
                                                       value="{{$class->id}}"
                                                       name="classesIDs[]" {{(in_array($class->id, $userClassesID)) ? 'checked' : ''}}> {{$class->name}}
                                            </label>
                                        </div>
                                    </div>
                                @endforeach
                            @else
                                No Class found.
                            @endif
                        </div>
                        <div>
                            <div class="text-right">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@stop

@section('css')
    @include('admin.css')
@stop
@section('js')
    @include('admin.javascript')
    <script>
        $(document).ready(function () {
            $(document).on('submit', 'form#classesForm', function (e) {
                e.preventDefault();
                var $this = this;
                // ajax_request($($this).attr('action'), $($this), 'POST');
                startLoading();
                var form = $($this)[0];
                var data = new FormData(form);
                $.ajax({
                    url: $($this).attr('action'),
                    data: data,
                    enctype: 'multipart/form-data',
                    method: 'POST',
                    processData: false,
                    contentType: false,
                    cache: false,
                    success: function (data) {
                        var result = data;
                        new Noty({
                            type: 'success',
                            layout: 'topRight',
                            text: result.message
                        }).show();

                        stopLoading();

                    },

                    error: function (data) {

                        stopLoading();

                        var result = JSON.parse(data.responseText);

                        $.each(result.errors, function (k, v) {
                            new Noty({
                                type: 'error',
                                layout: 'topRight',
                                text: v
                            }).show();
                        });
                    }

                });
                return false;
            });
        });
    </script>
@stop

resources/views/admin/user/create.blade.php
<div class="modal fade" id="create_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{route('admin.'.$customData['routeName'].'.store')}}" method="post" class="create-form">
                @include('admin.user.partial.form', ['label' => 'Create'])
            </form>
        </div>
    </div>
</div>

resources/views/admin/user/edit.blade.php
<div class="modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{route('admin.'.$customData['routeName'].'.index')}}" method="post" class="edit-form">
                {{method_field('PUT')}}
                @include('admin.user.partial.form', ['label' => 'Edit'])
                <input type="hidden" name="id" id="id" value=""/>
            </form>
        </div>
    </div>
</div>

resources/views/admin/user/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>{{$customData['title']['plural']}} List
        <button class="btn btn-primary modalOpens" data-toggle="modal" data-target="#create_modal">Create
            {{$customData['title']['singular']}}
        </button>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active">{{$customData['title']['plural']}}</li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                @include('admin.user.partial.searchForm')
            </div>
        </div>
        <div class="col-md-12">
            <div class="box">
                <div class="box-body" id="ajax-container">
                    @include('admin.user.listing')
                </div>
            </div>
        </div>
    </div>
    @include('admin.user.create')
    @include('admin.user.edit')
    <div id="ajaxModals"></div>
@stop

@section('css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @include('admin.css')
@stop

@section('js')
    @include('admin.javascript')
    <script>
        var errorHandler = function (data) {
            stopLoading();
            var result = JSON.parse(data.responseText);
            $.each(result.errors, function (k, v) {
                new Noty({
                    type: 'error',
                    layout: 'topRight',
                    text: v
                }).show();
            });
        };
        var getClasses = function () {
            var value = $('#teacher_school').val();
            startLoading();
            $.ajax({
                url: '{{route('admin.school_admin.classes')}}/' + value,
                data: {},
                method: 'GET',
                success: function (data) {
                    $('#teacher_class').html(data);
                    stopLoading();
                },
                error: function (data) {
                    stopLoading();
                    var result = JSON.parse(data.responseText);
                    $.each(result.errors, function (k, v) {
                        new Noty({
                            type: 'error',
                            layout: 'topRight',
                            text: v
                        }).show();
                    });
                }
            });

        };
        $(document).ready(function () {
            $('.create-form').submit(function (e) {
                e.preventDefault();

                var $url = $(this).attr('action'),
                    $self = $(this);

                ajax_request($url, $self, 'POST');

                return false;
            });
            $('.edit-form').submit(function (e) {
                e.preventDefault();

                var $url = $(this).attr('action') + '/' + $(this).find('input[name="id"]').val(),
                    $self = $(this);

                ajax_request($url, $self, 'PUT');

                return false;
            });
            $(document).on('click', '.edit_entry', function (e) {
                var attributes = $(this).data();
                attributes = attributes.props;
                $.each(attributes, function (k, v) {
                    if (k === 'classes') {
                        if (v.length > 0) {
                            v = v[0];
                        }
                        $('.edit-form #school_class').val(v.id);
                    }
                });
            });
            $(document).on('click', '.assignSchoolBtn', function (e) {
                e.preventDefault();
                var entryID = $(this).data().entry_id;
                $.ajax({
                    url: '{{route('admin.user.assignSchoolModalIndex')}}/' + entryID,
                    method: 'GET',
                    data: {},
                    success: function (data) {
                        $('#ajaxModals').html(data);
                        $('#assignSchoolModal').modal('show');
                        stopLoading();
                    },
                    error: errorHandler
                });
                return false;
            });
            $(document).on('click', '.assignClassBtn', function (e) {
                e.preventDefault();
                var entryID = $(this).data().entry_id;
                $.ajax({
                    url: '{{route('admin.user.assignClassModalIndex')}}/' + entryID,
                    method: 'GET',
                    data: {},
                    success: function (data) {
                        $('#ajaxModals').html(data);
                        $('#assignClassModal').modal('show');
                        stopLoading();
                    },
                    error: errorHandler
                });
                return false;
            });
            $(document).on('click', '.assignChildrenBtn', function (e) {
                e.preventDefault();
                var entryID = $(this).data().entry_id;
                $.ajax({
                    url: '{{route('admin.user.assignChildrenModalIndex')}}/' + entryID,
                    method: 'GET',
                    data: {},
                    success: function (data) {
                        $('#ajaxModals').html(data);
                        $('#assignChildrenModal').modal('show');
                        stopLoading();
                    },
                    error: errorHandler
                });
                return false;
            });
        });
    </script>
@stop

resources/views/admin/user/listing.blade.php
<div class="table-responsive">
    <table id="example" class="table table-bordered table-hover tablesorter customTableSort">
        <thead>
        <tr>
            <th>ID</th>
            <th>Image</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Role</th>
            @if($customData['routeName'] === 'teacher')
                <th>School</th>
            @endif
            <th>Created At</th>
            <th>Action(s)</th>
        </tr>
        </thead>
        <tbody>
        @if (!empty($users))
            @foreach ( $users as $user )
                <tr id="user_{{$user->id}}">
                    <td>{{$user->id}}</td>
                    <td>
                        <img src="{{($user->image) ? asset('/images/users/'.$user->roles[0]->name.'/'.$user->image) : asset('/images/userDefaultIcon.png')}}"
                             class="avatar">
                    </td>
                    <td>{{$user->name}}</td>
                    <td>{{($user->email) ? $user->email : 'N/A'}}</td>
                    <td>{{$user->phone_number}}</td>
                    <td>{{($user->roles[0]->display_name) ? $user->roles[0]->display_name : $user->roles[0]->name}}</td>
                    @if($customData['routeName'] === 'teacher')
                        <td>{{(!empty($user->schools) && count($user->schools) > 0) ? $user->schools[0]->name : 'N/A'}}</td>
                    @endif
                    <td class="created_at">{{($user->created_at) ? $user->created_at->diffForHumans() : 'N/A'}}</td>
                    <td>
                        <div class="btn-group">
                            @if($user->roles[0]->name === 'school_admin')
                                <a class="btn btn-sm btn-primary" href="{{route('admin.school_admin.classes', [
                                    'school_id' => $user->id
                                ])}}">
                                    Assign Classes
                                </a>
                            @elseif($user->roles[0]->name === 'teacher' || $user->roles[0]->name === 'student_child')
                                @if(Auth::user()->hasRole('super_admin'))
                                    <a href="#" class="btn btn-sm btn-primary assignSchoolBtn"
                                       data-entry_id="{{$user->id}}">
                                        Assign School
                                    </a>
                                    @if(!empty($user->schools && count($user->schools) > 0))
                                        <a href="#" class="btn btn-sm btn-primary assignClassBtn"
                                           data-entry_id="{{$user->id}}">
                                            Assign Class
                                        </a>
                                    @endif
                                @else
                                    <a href="#" class="btn btn-sm btn-primary assignClassBtn"
                                       data-entry_id="{{$user->id}}">
                                        Assign Class
                                    </a>
                                @endif
                            @elseif($user->roles[0]->name === 'parent')
                                <a href="#" class="btn btn-sm btn-primary assignChildrenBtn"
                                   data-entry_id="{{$user->id}}">
                                    Assign Children
                                </a>
                            @endif
                            <a class="btn btn-sm btn-primary edit_entry modalOpens" title="Edit" href="#"
                               data-props="{{$user}}"
                               data-toggle="modal" data-target="#edit_modal">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a class="delete btn btn-sm btn-danger entry_remove"
                               data-route="{{route('admin.'.$customData['routeName'].'.index')}}"
                               data-entry_id="{{$user->id}}"
                               title="Delete">
                                <i class="fa fa-remove"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="4">There is no {{$customData['title']['singular']}}.</td>
            </tr>
        @endif
        </tbody>
        <tfoot>
        <tr>
            <th>ID</th>
            <th>Image</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Role</th>
            @if($customData['routeName'] === 'teacher')
                <th>School</th>
            @endif
            <th>Created At</th>
            <th>Action(s)</th>
        </tr>
        </tfoot>
    </table>
</div>

{{ $users->links() }}